### ISSUE TITLE
Gerar o boleto em PDF

### ISSUE THREAD

**Issue by eullercristian** [JotJunior/PHP-Boleto-ZF2#5]
Uma sugestão seria gerar o boleto em PDF. Estou desenvolvendo esta questão em meu projeto local, pois há um vírus que está afetando vários computadores, ele procura pela palavra boleto e muda o código de barras, banco e linha digitável, o cliente efetua o pagamento e o mesmo cai na conta do hacker.

**Comment by JotJunior** [comment]
Já há essa possibilidade. Se você colocar /pdf no final ele vai gerar o PDF. O problema é que o layout ainda está desconfigurado na hora de gerar o arquivo.

Em tempo, o boleto é gerado usando uma imagem na linha de código e uma imagem única no código de barras. Isso impede a alteração dos números via DOM.
