### ISSUE TITLE
Problemas ao instalar o projeto

### ISSUE THREAD

**Issue by eullercristian** [JotJunior/PHP-Boleto-ZF2#6]
Prezado, ao instalar o projeto tive o seguinte problema: http://puu.sh/hBgGV/bd1db4cee0.png

Veja como está meu composer.json, https://gist.github.com/eullercristian/fbd4686b028cb172f5cc

Poderia me ajudar a resolver esta questão?

**Comment by filpgame** [comment]
Aqui estou com o mesmo problema, o composer não encontra a dependência "dino/dompdf-module"

**Comment by JotJunior** [comment]
Basta acrescentar o  "dino/dompdf-module" : "dev-master"  no seu composer.json 
(eu não entendi por que não baixa a dependência automaticamente. Vou pesquisar para tentar resolver isso)
